---

- name: Store the remote IP address
  set_fact:
    remote_ip: '{{ hostvars[inventory_hostname]["ansible_default_ipv4"]["address"] }}'

- name: Check the type of IP address for the remote host
  set_fact:
    remote_ip_private: '{{ (remote_ip | ipaddr("private")) != None }}'

- name: Set the remote access firewall rules for public networks
  when: not remote_ip_private
  include_tasks: ufw-public-access.yml

- name: Set the remote access firewall rules for private networks
  when: system.devel and remote_ip_private
  include_tasks: ufw-private-access.yml

- name: Set the generic firewall rules
  include_tasks: ufw-generic-rules.yml

- name: Remove root password access from SSH
  when: security.ssh_disable_root_access_with_password
  tags: security
  notify: Restart SSH
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes'
    replace: 'PermitRootLogin without-password'
    mode: '0600'

- name: Lock root account
  tags: security
  user:
    name: root
    password_lock: '{{ security.lock_root_password }}'

- name: Remove users password access from SSH
  when: security.ssh_disable_users_access_with_password
  tags: security
  notify: Restart SSH
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication yes.*'
    replace: 'PasswordAuthentication no'
    mode: '0600'
