---

- name: Make sure the server can be accessed from the LAN
  ufw:
    proto: tcp
    port: 22
    src: '{{ cidr }}'
    rule: allow
    comment: Access SSH from the local ansible host (IPv4)
  loop: '{{ dev_lan_cidrs }}'
  loop_control:
    loop_var: cidr
