---

- name: Check if the fwknop-client package is installed
  register: fwknop
  stat:
    path: /usr/bin/fwknop

- name: Install fwknop client
  when: not fwknop.stat.exists
  become: true
  become_method: sudo
  tags: apt
  apt:
    name: fwknop-client

- name: Create a directory for fwknop backup if it does not exists
  file:
    path: '{{ backup_directory }}/fwknop/'
    state: directory

- name: Retrieve the key from the backup if exists
  shell: >-
    test -f '{{ backup_directory }}/fwknop/fwknoprc'
    && cp '{{ backup_directory }}/fwknop/fwknoprc'
    ~/.fwknop-{{ network.domain }}.rc
    || /bin/true
  args:
    creates: '~/.fwknop-{{ network.domain }}.rc'

- name: Generate the initial key pair on the client machine
  shell: >-
    fwknop -A tcp/22 -D main.{{ network.domain }}
    --key-gen --use-hmac --save-rc-stanza
    --rc-file ~/.fwknop-{{ network.domain }}.rc
  args:
    warn: false
    creates: '~/.fwknop-{{ network.domain }}.rc'

- name: Backup the key for next deployment
  shell: >-
    cp  ~/.fwknop-{{ network.domain }}.rc
    '{{ backup_directory }}/fwknop/fwknoprc'
  args:
    warn: false
    creates: '{{ backup_directory }}/fwknop/fwknoprc'

- name: Protect the file
  file:
    path: '{{ rcfile }}'
    mode: '0600'
  with_items:
    - '{{ backup_directory }}/fwknop/fwknoprc'
    - '~/.fwknop-{{ network.domain }}.rc'
  loop_control:
    loop_var: rcfile
