---

postfix_pkgs:
  - postfix
  - postfix-cdb
  - postfix-pcre
  - postfix-ldap
  - sasl2-bin
  - postfix-policyd-spf-python

postfix_apparmor_profiles:
  - usr.lib.postfix.anvil
  - usr.lib.postfix.bounce
  - usr.lib.postfix.cleanup
  - usr.lib.postfix.discard
  - usr.lib.postfix.error
  - usr.lib.postfix.flush
  - usr.lib.postfix.lmtp
  - usr.lib.postfix.local
  - usr.lib.postfix.master
  - usr.lib.postfix.nqmgr
  - usr.lib.postfix.oqmgr
  - usr.lib.postfix.pickup
  - usr.lib.postfix.pipe
  - usr.lib.postfix.proxymap
  - usr.lib.postfix.qmgr
  - usr.lib.postfix.qmqpd
  - usr.lib.postfix.scache
  - usr.lib.postfix.showq
  - usr.lib.postfix.smtp
  - usr.lib.postfix.smtpd
  - usr.lib.postfix.spawn
  - usr.lib.postfix.tlsmgr
  - usr.lib.postfix.trivial-rewrite
  - usr.lib.postfix.verify
  - usr.lib.postfix.virtual
  - usr.sbin.sendmail
  - usr.sbin.postdrop
  - usr.sbin.postqueue
  - usr.sbin.postalias
