---

# FIXME: The key conversion does not work anymore on Buster

- name: Install the required packages
  tags: apt
  apt:
    update_cache: true
    name: '{{ packages }}'
    state: present

- name: Copy the ssh public key for authentication
  copy:
    src: /root/.ssh/authorized_keys
    dest: /etc/dropbear-initramfs/authorized_keys
    remote_src: yes

- name: Remove dropbear default keys
  file:
    path: '/etc/dropbear-initramfs/{{ key.dest }}'
    state: absent
  with_items: '{{ keys_convert }}'
  loop_control:
    loop_var: key

- name: Convert the openssh key already existing for dropbear
  notify: Update initramfs
  shell: >-
    /usr/lib/dropbear/dropbearconvert openssh dropbear
    /etc/ssh/{{ key.src }} /etc/dropbear-initramfs/{{ key.dest }}
  args:
    creates: '/etc/dropbear-initramfs/{{ key.dest }}'
  with_items:
    - '{{ keys_convert }}'
  loop_control:
    loop_var: key

- name: Convert the openssh key already existing for dropbear
  notify: Update initramfs
  shell: >-
    /usr/lib/dropbear/dropbearconvert openssh dropbear
    /etc/ssh/{{ key.src }} /etc/dropbear/{{ key.dest }}
  args:
    creates: '/etc/dropbear/{{ key.dest }}'
  with_items:
    - '{{ keys_convert }}'
  loop_control:
    loop_var: key
