---

- name: Install required packages
  tags: apt
  apt:
    name:
      - fwknop-apparmor-profile
      - fwknop-server
    state: present

- name: Get the initial key from the client file
  delegate_to: localhost
  register: key_base64
  shell: >-
    set -o pipefail ;
    cat ~/.fwknop-{{ network.domain }}.rc
    | grep ^KEY_BASE64 | sed 's/^KEY_BASE64\s\+//'
  args:
    executable: /bin/bash

- name: Set the initial key
  notify:
    - Stop fwknop server
    - Restart fwknop server
  replace:
    path: /etc/fwknop/access.conf
    regexp: '^KEY_BASE64.*'
    replace: 'KEY_BASE64 {{ key_base64.stdout }}'

- name: Get the HMAC key from the client file
  delegate_to: localhost
  register: hmac_key_base64
  shell: >-
    set -o pipefail ;
    cat ~/.fwknop-{{ network.domain }}.rc
    | grep ^HMAC_KEY_BASE64
    | sed 's/^HMAC_KEY_BASE64\s\+//'
  args:
    executable: /bin/bash

- name: Set the HMAC key
  notify:
    - Stop fwknop server
    - Restart fwknop server
  replace:
    path: /etc/fwknop/access.conf
    regexp: '^HMAC_KEY_BASE64.*'
    replace: 'HMAC_KEY_BASE64 {{ hmac_key_base64.stdout }}'

- name: Set the HMAC key
  notify:
    - Stop fwknop server
    - Restart fwknop server
  lineinfile:
    path: /etc/fwknop/access.conf
    insertafter: '^HMAC_KEY_BASE64.*'
    line: 'REQUIRE_SOURCE_ADDRESS Y'

- name: Get the default NIC (IPv4 version)
  when: ansible_default_ipv4 is defined and ansible_default_ipv4.interface is defined
  set_fact:
    default_nic: '{{ ansible_default_ipv4.interface }}'

- name: Get the default NIC (IPv6 version)
  when: ansible_default_ipv6 is defined and ansible_default_ipv6.interface is defined
  set_fact:
    default_nic: '{{ ansible_default_ipv6.interface }}'

- name: Set the network interface
  notify:
    - Stop fwknop server
    - Restart fwknop server
  replace:
    path: /etc/fwknop/fwknopd.conf
    regexp: '^#?PCAP_INTF.*'
    replace: 'PCAP_INTF {{ default_nic }}'

- name: Allow to use a random port
  when: firewall.fwknop.port == 'random'
  notify:
    - Stop fwknop server
    - Restart fwknop server
  replace:
    path: /etc/fwknop/fwknopd.conf
    regexp: '^#?PCAP_FILTER\s*udp .*;'
    replace: 'PCAP_FILTER udp dst portrange 10000-65535;'

- name: Use a fixed port
  when: firewall.fwknop.port != 'random'
  notify:
    - Stop fwknop server
    - Restart fwknop server
  replace:
    path: /etc/fwknop/fwknopd.conf
    regexp: '^#?PCAP_FILTER\s*udp .*;'
    replace: 'PCAP_FILTER udp port {{ firewall.fwknop.port }};'

- name: Activate the daemon by default
  notify:
    - Stop fwknop server
    - Restart fwknop server
  replace:
    path: /etc/default/fwknop-server
    regexp: START_DAEMON="no"
    replace: START_DAEMON="yes"

- name: Create temporary directory before starting the service
  file:
    path: /var/fwknop
    state: directory

# I filled this bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911485
# The daemon trying to read /var/fwknop/fwknopd.pid might be a bug in the fwknop-server
- name: Add some missing permissions in the apparmor profile
  notify:
    - Restart AppArmor service
    - Stop fwknop server
    - Restart fwknop server
  tags: apparmor
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.fwknopd
    line: '{{ line }}'
    insertbefore: '^}'
    regexp: '{{ line }}'
  with_items:
    - '# Missing permissions added by homebox'
    - '  /run/xtables.lock rwk,'
    - '  /var/fwknop/fwknopd.pid r,'
    - '  /var/fwknop/fwknopd.pid wkl,'
    - '  /var/fwknop/digest.cache r,'
    - '  /var/fwknop/digest.cache wkl,'
  loop_control:
    loop_var: line
