---

- name: Activate AppArmor profile
  command: 'aa-enforce usr.sbin.nginx'

- name: Restart AppArmor service
  service:
    name: apparmor
    state: restarted

- name: Restart php-fpm
  service:
<<<<<<< HEAD
    name: php7.3-fpm
=======
    name: 'php{{ php_version }}-fpm'
>>>>>>> upstream/buster-dev
    state: restarted

- name: Restart nginx
  notify:
    - Restart IMAP proxy
    - Restart php-fpm
  service:
    name: nginx
    state: restarted
