---

- name: Create the web site
  tags: nginx
  notify:
    - Check nginx config
    - Restart nginx
  vars:
    csp: '{{ mail.antispam.webui.csp | default(csp_default) }}'
    fp: '{{ mail.antispam.webui.fp | default(fp_default) }}'
  template:
    src: nginx.conf
    dest: '/etc/nginx/sites-available/rspamd.{{ network.domain }}.conf'
    owner: root
    group: root
    mode: '0644'

- name: Copy rspamd configuration
  tags: nginx
  notify:
    - Check nginx config
    - Restart nginx
  file:
    src: '/etc/nginx/sites-available/rspamd.{{ network.domain }}.conf'
    dest: '/etc/nginx/sites-enabled/rspamd.{{ network.domain }}.conf'
    state: link

# AppArmor configuration ======================================================

- name: Install nginx AppArmor profile
  tags: rspamd, security, apparmor
  template:
    src: apparmor.d/local/rspamd-web
    dest: /etc/apparmor.d/local/nginx-rspamd-web

- name: Check if AppArmor nginx configuration already contains the line
  register: line_found
  shell: >-
    grep -c 'include <local/nginx-rspamd-web>'
    /etc/apparmor.d/usr.sbin.nginx
  changed_when: false
  failed_when: false

- name: Add rspamd AppAromor specific configuration
  when: line_found.stdout == '0'
  register: aa_config
  tags: rspamd, security, apparmor
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    line: '  #include <local/nginx-rspamd-web>'
    insertbefore: '# End of local includes for homebox'

- name: Activate AppArmor profiles
  when: aa_config.changed
  tags: rspamd, security, apparmor
  command: 'aa-enforce usr.sbin.nginx'
  notify: Restart AppArmor service
