---

sieve:
  global_scripts:
    - duplicate-checks.sieve
    - sent-checks.sieve
    - before-global.sieve
    - report-spam.sieve
    - report-ham.sieve
    - tags-important.sieve
    - draft-rules.sieve

# Default dovecot packages to install
dovecot:
  packages:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-managesieved
    - dovecot-sieve
    - dovecot-ldap
  fts_packages:
    - tomcat9
    - solr-tomcat
    - dovecot-solr
    - poppler-utils
    - catdoc
    - unzip
    - docx2txt
    - odt2txt
    - xlsx2csv
    - unrtf
    - gzip
    - p7zip-full
    - p7zip-rar
    - tnef
  access_check_packages:
    - grepcidr
    - sqlite3
  settings:
    mail_max_userip_connections: 64
    lda_mailbox_autocreate: no
    lda_mailbox_autosubscribe: no
  # Authorized characters for the username
  username_chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.-_@
