---

- name: Install isync package
  apt:
    name: '{{ pkgs }}'
    state: present
  vars:
    pkgs:
      - isync
      - libsasl2-modules

# Get the import master account password
- name: Initialise the import user password parameters
  set_fact:
    import_password_params: "{{ backup_directory }}/ldap/import.pwd {{ policies.system.password }}"

- name: Create the import master user account password
  no_log: true
  set_fact:
    import_password: '{{ lookup("password", import_password_params) }}'

- name: Build a template for each account and each user, and encrypt it using the system key
  include_tasks: isync-template.yml
  with_items:
    - '{{ users }}'
  loop_control:
    loop_var: user

- name: Copy the postlogin scripts to start emails import on each user login
  notify: Restart dovecot
  tags: scripts
  copy:
    src: import-emails
    dest: /etc/dovecot/login-scripts/500-import-emails
    mode: '0755'
    owner: root
    group: root
