---


- name: Create the weekly report cron job every sunday evening
  tags: cron
  cron:
    name: weekly-access-report
    day: '*'
    month: '*'
    hour: 23
    minute: 59
    weekday: 0
    job: >-
      /usr/local/bin/access-report.py
      --format {{ user.access_report.format | default("text,html") }}
      --recipient {{ user.access_report.recipient | default(user.uid) }}
      --period last-week
    user: '{{ user.uid }}'
    state: '{{ ("week" in user.access_report.periods) | ternary("present", "absent") }}'

- name: Set the monthly cron jobs for each configured user
  tags: cron
  cron:
    name: monthly-access-report
    day: 1
    hour: 1
    minute: 0
    job: >-
      /usr/local/bin/access-report.py
      --format {{ user.access_report.format | default("text,html") }}
      --recipient {{ user.access_report.recipient | default(user.uid) }}
      --period last-month
    user: '{{ user.uid }}'
    state: '{{ ("month" in user.access_report.periods) | ternary("present", "absent") }}'

- name: Set the yearly cron jobs for each configured user
  tags: cron
  cron:
    name: yearly-access-report
    day: 1
    hour: 1
    month: 1
    minute: 0
    job: >-
      /usr/local/bin/access-report.py
      --format {{ user.access_report.format | default("text,html") }}
      --recipient {{ user.access_report.recipient | default(user.uid) }}
      --period last-year
    user: '{{ user.uid }}'
    state: '{{ ("year" in user.access_report.periods) | ternary("present", "absent") }}'
