---

- name: Install the required packages
  apt:
    name: '{{ packages }}'
    state: present

- name: Copy the report templates
  copy:
    src: access-report.d
    dest: /etc/homebox

- name: Copy the reporting script
  tags: scripts
  copy:
    src: 'access-report.py'
    dest: '/usr/local/bin/access-report.py'
    mode: '0755'

- name: Add cron tasks for each users
  include_tasks: cron-tasks.yml
  with_items:
    - '{{ users | selectattr("access_report", "defined") | list }}'
    - uid: postmaster
      access_report:
        periods: [ 'week', 'month', 'year' ]
        format: 'text'
  loop_control:
    loop_var: user

- name: Install AppArmor profile for the script
  tags: security, apparmor
  register: aa_templates
  copy:
    src: apparmor.cf
    dest: '/etc/apparmor.d/usr.local.bin.access-report.py'

- name: Activate AppArmor profiles
  tags: security, apparmor
  notify: Restart AppArmor service
  command: 'aa-enforce usr.local.bin.access-report.py'
