---

- name: Add the SSH keys for users remote access
  tags: backup
  file:
    path: "/home/users/{{ user.uid }}/.ssh"
    owner: '{{ user.uid }}'
    group: users
    state: directory
    mode: '0700'
  with_items:
    - '{{ users | selectattr("backup_ssh_key", "defined") | list }}'
  loop_control:
    loop_var: user

- name: List the backup locations that can be mounted
  when: backup.locations is defined
  set_fact:
    mountable_backup_locations: '{{ backup.locations
                                    | selectattr("url", "defined")
                                    | rejectattr("url", "contains", "dir://")
                                    | rejectattr("url", "contains", "ssh://")
                                    | list }}'

- name: Add the backup folder for the users
  when: backup.locations is not defined or
        mountable_backup_locations == []
  tags: backup
  file:
    path: '/home/users/{{ user.uid }}/backup'
    owner: '{{ user.uid }}'
    group: users
    state: directory
    mode: '0700'
  with_items:
    - '{{ users | selectattr("backup_ssh_key", "defined") | list }}'
  loop_control:
    loop_var: user

- name: Use the first backup drive for the users
  when: backup.locations is defined and
        mountable_backup_locations != []
  set_fact:
    backup_root: 'mnt/backup/{{ mountable_backup_locations[0].name }}'
    backup_folder: ''

- name: Use the home root folder for the backup server
  when: backup.locations is not defined or
        mountable_backup_locations == []
  set_fact:
    backup_root: 'home/users'
    backup_folder: 'backup/'

- name: Create the folders for the user
  file:
    owner: '{{ user.uid }}'
    group: users
    path: '/{{ backup_root }}/{{ user.uid }}/{{ backup_folder }}'
    state: directory
    mode: '0700'
  with_items:
    - '{{ users | selectattr("backup_ssh_key", "defined") | list }}'
  loop_control:
    loop_var: user

- name: Add the authorised key configuration
  authorized_key:
    user: '{{ user.uid }}'
    state: present
    key: >-
      {{ user.backup_ssh_key.type }}
      {{ user.backup_ssh_key.data | regex_replace(" ") }}
      {{ user.backup_ssh_key.comment }}
    key_options: >-
      command="borg serve
      --restrict-to-path
      /{{ backup_root }}/{{ user.uid }}/{{ backup_folder }}",restrict
  with_items:
    - '{{ users | selectattr("backup_ssh_key", "defined") | list }}'
  loop_control:
    loop_var: user
