---

- name: Add Python milter library
  tags: apt
  apt:
    name: '{{ packages }}'
    state: present

- name: Create a directory for the SOGo milter
  file:
    path: '{{ path }}'
    state: directory
    owner: postfix
    group: postfix
  with_items:
    - /var/lib/milter-sogo-abook
    - /run/milter-sogo-abook
  loop_control:
    loop_var: path

- name: Initialise the sogo database read-only password parameters
  tags: facts
  set_fact:
    sogo_password_params: >-
      {{ backup_directory }}/postgresql/sogo_ro.pwd
      {{ policies.system.password }}

- name: Create the sogo read-only database account password
  tags: facts
  no_log: true
  set_fact:
    sogo_db_ro_password: '{{ lookup("password", sogo_password_params) }}'

- name: Create the read-only database user
  tags: postgres
  become: true
  become_user: postgres
  postgresql_user:
    name: sogo_ro
    db: sogo
    password: '{{ sogo_db_ro_password }}'
    role_attr_flags: LOGIN

- name: Grant read only to all tables
  tags: postgres
  become: true
  become_user: postgres
  postgresql_privs:
    db: sogo
    role: sogo_ro
    objs: ALL_IN_SCHEMA
    priv: SELECT

- name: Create the configuration file
  notify:
    - Reload systemd
    - Restart milter service
  template:
    src: milters.conf
    dest: /etc/sogo/milters.conf
    owner: sogo
    group: postfix
    mode: '0640'

- name: Add the milter service
  notify:
    - Reload systemd
    - Reload postfix
    - Restart milter service
  copy:
    src: milter-abook.py
    dest: /usr/local/bin/milter-sogo-abook.py
    mode: '0755'

- name: Copy the address book search milter
  notify:
    - Reload systemd
    - Reload postfix
  template:
    src: milter-abook.service
    dest: /etc/systemd/system/milter-sogo-abook.service
    mode: '0644'
