---

roundcube:
  url: 'webmail.{{ network.domain }}'
  title: 'Roundcube Webmail ({{ ldap.organization.domain }})'
  enigma: no
  max_attachment_size: 25   # In megabytes
  plugins: '{{ roundcube_plugins }}'


# nginx security headers for the webmail
# this cannot be overriden
# The header X-Frame-Options is already set by the roundcube code
nginx_sec_headers:
  - id: Strict-Transport-Security
    value: max-age=31536000
  - id: X-Content-Type-Options
    value: nosniff
  - id: Referrer-Policy
    value: same-origin

####
csp_default:
  default: "'none'"
  list:
    - id: default-src
      value: "https: 'self'"
    - id: script-src
      value: "https: 'self' 'unsafe-inline' 'unsafe-eval'"
    - id: img-src
      value: "https: 'self' 'unsafe-inline'"
    - id: style-src
      value: "https: 'self' 'unsafe-inline'"
    - id: media-src
      value: "https: 'self'"
    - id: font-src
      value: "https: data: 'self'"
    - id: base-uri
      value: "https: 'self'"
    - id: frame-src
      value: "https: 'self'"
    - id: object-src
      value: "https: 'self'"
    - id: connect-src
      value: "https: 'self'"


### Features policy
# See https://github.com/w3c/webappsec-feature-policy
# Set to 'none' by default
fp_default:
  default: "'none'"
  list:
    - id: notifications
      value: "https: 'self'"
    - id: push
      value: "https: 'self'"
    - id: sync-xhr
      value: "https: 'self'"
    - id: geolocation
    - id: midi
    - id: microphone
    - id: camera
    - id: magnetometer
    - id: gyroscope
    - id: speaker
    - id: vibrate
    - id: fullscreen
    - id: payment
