---

# Remove packages that are not needed for a live system:
# bash-completion:
# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825153
# this seems to remove most errors like :
# <passwd="*"> request denied by validnames option.

cleanup_packages:
  - bash-completion
  - resolvconf

#############################################################################
# Limits tuning for the mail users group members
# These limits should be fine for users belonging to the "mail_users" group.
# If you need an administrator with higher limits, create a specific account
# Remember the maximum file size is the size of an email; 100MB should be fine.
limits:
  users:
    memlock: 64         # Maximum locked-in-memory address space: 64KB
    nproc: 100          # Maximum number of processes: 100
    nofile: 2048        # Maximum number of open file descriptors: 2048
    maxlogins: 20       # Maximum number of logins
    data: 524288        # Maximum data size: 512M
    fsize: 131072       # Maximum file size: 128MB

# Tuning on a live system
# nofile: lsof -u <user> | wc -l
