---

- name: Install the package to manipulate the databases
  register: psycopg2_pkg
  tags: apt
  apt:
    name: python-psycopg2
    state: installed

- name: Stop the Zabbix server
  service:
    name: zabbix-server
    state: stopped

- name: Remove the packages previously installed packages
  tags: apt
  apt:
    name: "{{ zabbix_pkgs }}"
    state: absent

- name: Remove the nginx frontend
  tags: nginx
  notify:
    - Restart nginx
    - Restart php-fpm
  file:
    path: '{{ path }}'
    state: absent
  with_items:
    - '/etc/nginx/sites-available/zabbix.{{ network.domain }}.conf'
    - '/etc/nginx/sites-enabled/zabbix.{{ network.domain }}.conf'
  loop_control:
    loop_var: path

# AppArmor configuration ======================================================

- name: Remove AppArmor profiles
  notify:
    - Restart AppArmor service
    - Restart nginx
  tags: zabbix, security, apparmor
  file:
    path: '/etc/apparmor.d/{{ file }}'
    state: absent
  with_items:
    - local/nginx-zabbix
    - usr.sbin.zabbix_agentd
    - usr.sbin.zabbix_server
  loop_control:
    loop_var: file

- name: Remove AppArmor nginx entry
  tags: zabbix, security, apparmor
  notify:
    - Restart AppArmor service
    - Restart nginx
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    regexp: '^\s+#include <local/nginx-zabbix>'
    state: absent

# End of AppArmor configuration ===============================================

- name: Remove the database
  register: zabbixdb
  tags: postgres
  become: true
  become_user: postgres
  postgresql_db:
    name: zabbix
    state: absent

- name: Remove the database user
  tags: postgres
  become: true
  become_user: postgres
  postgresql_user:
    name: zabbix
    state: absent

- name: Remove all Zabbix configuration
  tags: config
  file:
    path: /etc/zabbix
    state: absent

- name: Remove the zabbix server FQDN from the host file
  tags: hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1\s+zabbix.{{ network.domain }}$'
    state: absent

- name: Remove the python / psycopg2 package
  when: psycopg2_pkg.changed and not system.devel
  tags: apt
  apt:
    name: python-psycopg2
    state: absent
