
- name: Restart dovecot
  tags: dovecot
  notify: Compile global sieve scripts
  service:
    name: dovecot
    state: restarted

- name: Compile global sieve scripts
  tags: dovecot
  command: '/usr/bin/sievec /etc/dovecot/sieve/{{ file }}'
  with_items:
    - '{{ sieve.global_scripts }}'
  loop_control:
    loop_var: file


- name: Restart AppArmor service
  service:
    name: apparmor
    state: restarted

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Restart tomcat
  service:
    name: tomcat9
    state: restarted
